version: "3.7"
services:
  findifyapp:
    build:
      context: .
      dockerfile: docker_spring.Dockerfile
    ports:
      - "9091:9091"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://findifydb:5432/findify_db
      SPRING_DATASOURCE_USERNAME: findify
      SPRING_DATASOURCE_PASSWORD: findify
  findifydb:
    image: postgres:12.2
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: findify_db
      POSTGRES_USER: findify
      POSTGRES_PASSWORD: findify

volumes:
  pgdata:
