version: "3.7"
services:
  db:
    build:
      context: .
      dockerfile: docker_db.Dockerfile
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
  server:
    build:
      context: .
      dockerfile: docker_spring.Dockerfile
    restart: always
    ports:
      - 9091:9091

volumes:
  pgdata: